### ISSUE TITLE
vercelデプロイエラー(画像の問題？)

### ISSUE THREAD

**Issue by developerhost** [akane11161218/tototyann-portfolio#1]
ここからどのcommitで失敗してるか見れるから、❌️を押してvercelの画面に移動してエラー内容を見ると原因がわかるかも！

https://github.com/akane11161218/tototyann-portfolio/commits/main/

**Comment by developerhost** [comment]
ここのリンクから飛んでVercelのエラーを見てみて！


https://vercel.com/akane11161218s-projects/tototyann-portfolio/7XKgmGRtg9NADjcHDdkAd7rSAZEk

**Comment by akane11161218** [comment]
![2024-08-13 23 17の画像](https://github.com/user-attachments/assets/97f4c9f8-f582-4974-b289-17dff1904a43)
